// Package spotify orchestrates go-librespot (github.com/devgianlu/go-librespot,
// GPL-3.0) as a separate, systemd-managed process: MuPiBox-NG never
// implements the Spotify protocol itself, only drives go-librespot's local
// REST/WebSocket API. See docs/spotify.md and the Phase 3A architecture
// report for the full design.
package spotify

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Config is the subset of go-librespot's config.yml MuPiBox-NG controls.
// Everything else keeps go-librespot's own defaults.
type Config struct {
	// ConfigDir is go-librespot's -config_dir: it holds config.yml and the
	// state.json go-librespot writes itself (player state and, if
	// PersistCredentials is set, the paired account's credentials).
	ConfigDir string
	// AudioDevice is settings.Audio.Device verbatim (an mpv --audio-device
	// value, e.g. "alsa/dmix:CARD=MAX98357A,DEV=0" or "auto"/""); WriteConfig
	// converts it to go-librespot's plain ALSA PCM syntax via ALSADeviceFromMPV.
	AudioDevice string
	// DeviceName is what shows up in the Spotify Connect device list.
	DeviceName string
	// APIPort is the local-only REST/WebSocket API port (127.0.0.1 only,
	// never exposed on the network -- consistent with mupibox-system-agent
	// staying off any network listener).
	APIPort int
	// PersistCredentials keeps the paired account across restarts (state.json)
	// instead of requiring the user to re-pair from the Spotify app every
	// time the box restarts.
	PersistCredentials bool
}

const DefaultAPIPort = 3678

// ALSADeviceFromMPV converts settings.Audio.Device (an mpv --audio-device
// value, e.g. "alsa/dmix:CARD=MAX98357A,DEV=0" or the mpv-only "auto") into
// the plain ALSA PCM name go-librespot's audio_device expects (its
// audio_backend is set separately to "alsa", so no "alsa/" prefix). Both
// mpv and go-librespot ultimately resolve device names via the same ALSA
// PCM namespace shown by `aplay -L`, so the same configured PCM (typically
// a dmix device -- see docs/mupihat.md's "dmix instead of plughw") plays
// through both without a second, independent audio path.
func ALSADeviceFromMPV(device string) string {
	switch device {
	case "", "auto":
		return "default"
	}
	if rest, ok := strings.CutPrefix(device, "alsa/"); ok {
		return rest
	}
	return device
}

// WriteConfig renders go-librespot's config.yml. Idempotent: safe to call on
// every mupibox-ng start, it always rewrites the file from the current
// settings (mirrors how mpv's --audio-device is re-derived from
// settings.Audio.Device on every start rather than hand-edited).
func WriteConfig(cfg Config) error {
	if cfg.ConfigDir == "" {
		return fmt.Errorf("spotify: config dir is required")
	}
	if err := os.MkdirAll(cfg.ConfigDir, 0700); err != nil {
		return fmt.Errorf("spotify: create config dir: %w", err)
	}
	port := cfg.APIPort
	if port == 0 {
		port = DefaultAPIPort
	}
	deviceName := cfg.DeviceName
	if deviceName == "" {
		deviceName = "MuPiBox"
	}
	audioDevice := ALSADeviceFromMPV(cfg.AudioDevice)
	content := fmt.Sprintf(`# Generated by mupibox-ng. Do not edit by hand -- rewritten on every start
# from settings.Audio.Device (see internal/providers/spotify).
device_name: %s
device_type: speaker
audio_backend: alsa
audio_device: %s
zeroconf_enabled: true
zeroconf_backend: builtin
credentials:
  type: zeroconf
  zeroconf:
    persist_credentials: %t
server:
  enabled: true
  address: 127.0.0.1
  port: %d
`, yamlString(deviceName), yamlString(audioDevice), cfg.PersistCredentials, port)
	path := filepath.Join(cfg.ConfigDir, "config.yml")
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0600); err != nil {
		return fmt.Errorf("spotify: write config: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("spotify: replace config: %w", err)
	}
	return nil
}

// yamlString quotes a scalar for safe embedding in the generated YAML --
// device names/ALSA device strings are operator-controlled (settings.Audio.Device,
// admin-entered device name), not arbitrary untrusted input, but quoting
// avoids any YAML special-character surprises (":", "#", leading "-", ...).
func yamlString(s string) string {
	out := make([]byte, 0, len(s)+2)
	out = append(out, '"')
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			out = append(out, '\\')
			out = append(out, string(r)...)
		case r == '\n':
			out = append(out, `\n`...)
		case r == '\r':
			out = append(out, `\r`...)
		case r == '\t':
			out = append(out, `\t`...)
		case r < 0x20:
			// Any other control character: drop it rather than emit it
			// literally inside a double-quoted YAML scalar, where a raw
			// line break could otherwise let a crafted device name break
			// out onto a new YAML line.
		default:
			out = append(out, string(r)...)
		}
	}
	out = append(out, '"')
	return string(out)
}
